<?php defined('BASEPATH') OR exit('No direct script access allowed');

class User extends SERVICE_Controller {

    public function __construct($config = array())
    {
        parent::__construct();

        // echo parent::TESTVAR;

        $this->load->model('User_master_model');
        log_message('debug', json_encode($this->post()));
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }


    private function total_list()
    {
        return $this->User_master_model->selectTableTotal();
    }

    public function total_list_get()
    {
        // sleep(10);
        // var_dump(parent::getClientType());
        $resultData = $this->total_list();

        REST_Controller::set_response([
            'name' => 'total_list',
            'state' => true,
            'result' => $resultData,
            // 'user_token' =>  $this->Authorization
        ], REST_Controller::HTTP_OK);
        return;
    }
}
