<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Basic extends SERVICE_Controller {

    public function __construct($config = array())
    {
        parent::__construct();

		$this->load->model('Code_master_model');

    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function index_get()
    {
        parent::responseOutputMaster(
            'HTTP_OK',
            'Basic API'
        );
        return;
    }

    public function data_get()
    {

        $selectResult = $this->Code_master_model->selectTable();

        $codeListArray = [];
        $tmpCodeList = [];

        if($selectResult['status'] == true)
        {
            foreach ($selectResult['data'] as $arrayKey => $arrayValue) {

                $code_id = trim($arrayValue['code_id']);
                $group_id = trim($arrayValue['group_id']);
                $code_name = trim($arrayValue['code_name']);
                $code_comment = trim($arrayValue['code_comment']);

                if($group_id)
                {
                    if(!array_key_exists($group_id, $codeListArray))
                    {
                        $codeListArray[$group_id] = [];
                    }
                    // $codeListArray[$group_id] = [
                    //     'code_id' => $code_id,
                    //     'code_name' => $code_name,
                    //     'code_comment' => $code_comment,
                    // ];

                    array_push($codeListArray[$group_id], [
                        'code_id' => $code_id,
                        'code_name' => $code_name,
                        'code_comment' => $code_comment,
                    ]);
                }
            }
        }

        parent::responseOutputMaster(
            [
                'code_list' => $codeListArray
            ]
        );
        return;
    }


}
