<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Code extends SERVICE_Controller {

    public function __construct($config = array())
    {
        parent::__construct();

		$this->load->model('Code_master_model');

    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function index_get()
    {
        $this->response($resData, REST_Controller::HTTP_BAD_REQUEST);
    }

    public function list_get()
    {

        $selectResult = $this->Code_master_model->selectTable();

        $codeListArray = array();
        $tmpCodeList = array();

        if($selectResult['status'] == true)
        {
            foreach ($selectResult['data'] as $arrayKey => $arrayValue) {

                $tmpCodeList = array();

                $code_id = trim($arrayValue['code_id']);
                $group_id = trim($arrayValue['group_id']);
                $code_name = trim($arrayValue['code_name']);
                $code_comment = trim($arrayValue['code_comment']);

                if($group_id)
                {
                    $tmpCodeList = [
                        'code_id' => $code_id,
                        'code_name' => $code_name,
                        'code_comment' => $code_comment,
                    ];

                    // print_r($tmpCodeList);

                    if(!array_key_exists($group_id, $codeListArray))
                    {
                        $codeListArray[$group_id] = array();
                    }

                    // if(!array_key_exists($code_id, $codeListArray[$group_id]))
                    // {
                    //     $codeListArray[$group_id][$code_id] = array();
                    // }

                    // array_merge($codeListArray[$group_id], $tmpCodeList);

                    $codeListArray[$group_id][] = [
                        'code_id' => $code_id,
                        'code_name' => $code_name,
                        'code_comment' => $code_comment,
                    ];


                }




            }
            // array_push($codeListArray, $tmpCodeList);
        }


        parent::normalResponseOutput(
            '정상 전송하였습니다.',$codeListArray
        );
        return;
    }


}
