<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Timeline extends SERVICE_Controller {
	
	private $tokenCheck;
	private $tokenData;
	private $tokenUserUid;
	
	public function __construct($config = array())
	{
		parent::__construct();
		
		$this->load->model('User_master_model');
		$this->load->model('User_profile_master_model');
		$this->load->model('User_personal_profile_master_model');
		$this->load->model('Master_model');
		log_message('debug', json_encode($this->post()));
		
		$this->tokenCheck = parent::getTokenDecodeResult();
		$this->tokenData = parent::getTokenDecodeData();
		
		if($this->tokenCheck == false) {
			parent::responseErrorOutputMaster(
				'정상 적인 접근이 아닙니다.',
				'406',
				[
					'token' => '정상적인 토근이 아닙니다.'
				]
			);
			return;
		}
		
		$this->tokenUserUid = $this->tokenData->user_uid;
	}
	
	public function __destruct()
	{
		parent::__destruct(); // TODO: Change the autogenerated stub
	}
	
	public function user_get()
	{
		var_dump($this->tokenCheck);
		var_dump($this->tokenData);
		var_dump($this->tokenUserUid);
	}
	
	public function today_post()
	{
	
	}
	
	
	
	
}